### PR TITLE
update front matter and quarto listing

### PR DESCRIPTION
**Pull request by dweng0**
Fix issue with nested items not showing on consensus sub menu

### CODE REVIEW

**Comment by dweng0** [comment]
[Screencast from 2024-02-29 13-13-32.webm](https://github.com/autonity/docs.autonity.org/assets/5268627/1966eb4f-1c32-4b75-b43b-bc7e74dae5c1)

**Comment by dweng0** [comment]
And a small fix to padding for the callout accordions that i noticed while testing (and its in the vid at the end).

image

**Review by aiman — APPROVED** [review]
LGTM

**Review by jay-cousins — APPROVED** [review]
👍 LGTM

**Pull request merged**
