### PR TITLE
Update docs for rendering generated docs

### PR DESCRIPTION
**Pull request by dweng0**
This PR is part of an ongoing effort to enhance the display of automatically generated documentation. It introduces several key improvements to navigation, styling, and organization. The focus is on making sure the generated documentation renders correctly, whilst setting a foundation to build off for styling later on.

This PR depends on the merge of <https://github.com/autonity/docs.autonity.org/pull/220> for devenv implementation

### Summary of Changes:
- Navigation Enhancement: Added a Lua script to implement "previous" and "next" buttons at the bottom of each article for smoother navigation.
-  Styling Updates: Made minor styling adjustments, utilizing root variables to simplify planned future styling modifications.
-  Quarto Configuration Update: Streamlined the _quarto.yml by removing unused configurations and adjusting the setup to support a new "contracts" section.
- Example Contracts: Included two sample contracts for review purposes. **These will be removed in a future update.**
-  Image Updates: Updated the images, using images from [Autonity media kit](https://github.com/autonity/autonity-media-kit), ensuring consistency across documentation.
- Updated to add tags for function's mutation type (payable, view, pure)
- Updated to include 4-byte for uniqueness when overloading.

### CODE REVIEW

**Review by jay-cousins — COMMENTED** [review]
Should this be going into `develop` not `master`?

**Comment by dweng0** [comment]
> Should this be going into `develop` not `master`?

We dont have a develop branch. Perhaps this is something we need

**Review by jay-cousins — CHANGES_REQUESTED** [review]
I think this looks good.  I understand the pages will be removed after the PR is merged - but having the test contracts (which appear under **Contracts** in the navigation) rendering on live in the current position at the top of the page index looks strange. 

I.e. the hierarchy is **Getting started**, **Contracts**, **Concepts**.

Can the **Contracts** section at least be put in the Reference section?

**Comment by dweng0** [comment]
Yeah i think we need to setup gh pages as a staging server, and to create a develop branch that publishes to gh pages.

**Comment by dweng0** [comment]
> I think this looks good. I understand the pages will be removed after the PR is merged - but having the test contracts (which appear under **Contracts** in the navigation) rendering on live in the current position at the top of the page index looks strange.
> 
> I.e. the hierarchy is **Getting started**, **Contracts**, **Concepts**.
> 
> Can the **Contracts** section at least be put in the Reference section?

Updated!

image

**Review by jay-cousins — APPROVED** [review]
OK. On the method signature heading, I'm not sure if adding the datatype of the method signature param is over user friendly as the number of params grows, but that can be reviewed in another PR.

**Comment by dweng0** [comment]
yeah no that will change with the 4-byte update coming from @szemate

**Comment by aiman** [comment]
As discussed with @dweng0 a total site redesign is out of scope of current project. While visually it's a great start, there are many issues that need to be ironed out before rolling out. So split out the visual redesign into a separate branch, and create a new one limited to the scope of changes that we need for automated generation of Solidity docs.

**Comment by dweng0** [comment]
> As discussed with @dweng0 a total site redesign is out of scope of current project. While visually it's a great start, there are many issues that need to be ironed out before rolling out. So split out the visual redesign into a separate branch, and create a new one limited to the scope of changes that we need for automated generation of Solidity docs.

@aiman  I've split this out so that the changes that focus on the auto generated documentation can be found here <https://github.com/autonity/docs.autonity.org/pull/229> 

I will close this PR

**Pull request closed without merging**
