### PR TITLE
make the 4 byte text less prominent

### PR DESCRIPTION
**Pull request by dweng0**
This PR adds some styling to the 4byte text so that it is not as prominent as the method title.

### Current styling applied
image

### With styling applied explicitly for the 4byte text
image

### CODE REVIEW

**Comment by aiman** [comment]
Can we try showing the 4byte on the far right hand-side, in a box to the right of the visibility? This is because it's just noise for most users until it matters. Rather than being an essential piece of information users are looking for.

**Comment by dweng0** [comment]
@aiman 
image

**Comment by cmjc** [comment]
I really like having the 4 byte signature, but could it have a label for UX?  e.g. "4-byte Function Signature"?

**Review by jay-cousins — COMMENTED** [review]
I really like having the 4 byte signature, but could it have a label for UX?  e.g. "4-byte Function Signature"?  Or alternatively as a hover over text?

**Comment by aiman** [comment]
> I really like having the 4 byte signature, but could it have a label for UX? e.g. "4-byte Function Signature"? Or alternatively as a hover over text?

Why would somebody that is reading the Protocol Contract reference section need a label to explain the meaning of the 4-byte function selector? I don't think there is any need for this.

**Comment by aiman** [comment]
> to the right of the visibility

Thanks @dweng0 but can we try "to the right of the visibility" box as requested?

**Comment by dweng0** [comment]
@aiman  I have updated the PR. the changes can be viewed locally by going to the example contract:
<http://localhost:3000/reference/contracts/test.html>

image
(note that visibility and 4-byte values are dummy data)

**Review by jay-cousins — APPROVED** [review]
lgtm

**Review by szemate — APPROVED** [review]

**Comment by aiman** [comment]
Good to merge @dweng0

**Pull request merged**
