### PR TITLE
Rename "Autonity Utility Tool (aut)" to "Autonity CLI" throughout the docs

### PR DESCRIPTION
**Pull request by szemate**
The "Autonity Utility Tool" a.k.a. "aut" has been rebranded as "Autonity CLI" and its repository URL and installation URL have been changed.

Update the naming and the URLs.

### CODE REVIEW

**Review by jay-cousins — DISMISSED** [review]
LGTM

**Comment by aiman** [comment]
Thanks! However we'll need to merge this to `master`. @szemate can you also set target branch to `master`, a rebase may be required in case of conflicts...

**Comment by szemate** [comment]
> @szemate can you also set target branch to master, a rebase may be required in case of conflicts...

Done. Luckily, there were no conflicts.

**Comment by aiman** [comment]
Great!

**Pull request merged**
